### PR TITLE
Change Noblog.org into Noblogs.org

### PR DESCRIPTION
**Pull request by rakino**

### CODE REVIEW

**Comment by tonghuix** [comment]
感谢修正！

**Comment by rakino** [comment]
> 感谢修正！

举手之劳
`And...is it necessary to install a Chinese IME?`

**Comment by tonghuix** [comment]
> `And...is it necessary to install a Chinese IME?`

For what?

**Comment by rakino** [comment]
Daily use.

**Comment by tonghuix** [comment]
If you speak Chinese and communicate to someone who can understand Chinese excursively, I do suggest that installing a Chinese IME is better.

Otherwise, no need to install Chinese IME.

**Pull request merged**
